---
title: "Block Deasign"
author: "R Group"
date: "11/27/2021"
output: pdf_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library("support.CEs")
library(mltools)
library(data.table)

```



```{r}
rd = rotation.design( attribute.names = list(Brand = c("Sony", "Canon", "Nikon"),
                         `Sensor Size` = c("Full-Frame", "APS-H", "APS-C"),
                         `Camera Type` = c("DSLR", "Mirrorless"),
                         `Resolution` = c("64 megapixel", "24 megapixel", "12 megapixel"),
                         `Price` = c("$3,000", "$2,000", "$1,000")),
                          nalternatives = 2, nblocks = 1, seed = 123)

 
```
```{r}
alternative1 <-rd$alternatives$alt.1
alternative1=melt(alternative1,id.vars=c("BLOCK","QES","ALT"))
alternative1<- reshape(alternative1, idvar = c("BLOCK","QES","ALT","variable"), timevar = "ALT", direction = "wide")
alternative1
```


```{r}
alternative2 <-rd$alternatives$alt.2
alternative2=melt(alternative2,id.vars=c("BLOCK","QES","ALT"))
alternative2<- reshape(alternative2, idvar = c("BLOCK","QES","ALT","variable"), timevar = "ALT", direction = "wide")
alternative2
```


```{r}
data <- data.frame(cbind(alternative1,alternative2["value.2"]))
data<- data[order(data$QES),]
colnames(data) <- c('BLOCK','QES','Description','ALT1','ALT2')
data <- data[, c(3,4,5,2,1)]
data

```

```{r}
write.table(data, "survey_data.csv", row.names=FALSE, sep=",")
```













